image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off



install:
  - java -jar ./artifacts/app-ibank.jar -P:profile=test &
  - chod +x ./artifacts/app-ibank.jar

build_script:
  - chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true --info
